services:
  - type: web
    name: mortalidad-colombia
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13